### ISSUE TITLE
Rubber Ducky wont flash

### ISSUE THREAD

**Issue by TheAdventureGuy** [hak5darren/USB-Rubber-Ducky#109]
so i got my rubber ducky two days ago and i have tried to flash it with twinduck firmware, but there is an error when i try... i am sure the rubber ducky is in DFU mode.
![udklip](https://user-images.githubusercontent.com/18557374/38770078-b43aea82-3ffc-11e8-8244-cb504e3d3cb9.PNG)

**Comment by TheAdventureGuy** [comment]
never mind... it Works now

**Comment by user2618** [comment]
i have same problem

**Comment by Siegfried5** [comment]
are you holding the button?
