### ISSUE TITLE
Command key on OS X

### ISSUE THREAD

**Issue by maxvonhippel** [hak5darren/USB-Rubber-Ducky#13]
The instructions provided to not detail how to use command prompts on OS X.  For example, in order to open Spotlight on OS X I press the command key and the space bar at the same time.  Is there a way to do this with the Rubbery Ducky? (I hope so, because from the spotlight you can open any application, so this would be a very helpful tool)

**Comment by JPaulMora** [comment]
To access spotlight you can use *GUI* as the _Command_ button so ###GUI SPACE should do it for you.

The GUI command also means the _windows_ key

**Comment by maxvonhippel** [comment]
Hi John,

Actually I experimented and just typing Command Space works.

Thanks
Max

Ps like this
Command Space
STRING pages
ENTER

to open pages

**Comment by JPaulMora** [comment]
good to know, thanks for the replay!
