### ISSUE TITLE
Unknown license

### ISSUE THREAD

**Issue by beatussum** [hak5darren/USB-Rubber-Ducky#132]
I would like to know the license used for this repository. Is it **GPL**, **MIT** or something else?

Thank you in advance!

**Comment by dudeisbrendan03** [comment]
No license is referred to or specified, therefore it is ok to assume that it is [unlicensed](https://unlicense.org/).

**Comment by hak5darren** [comment]
Like Hak5, it's Creative Commons Attribution-NonCommercial-ShareAlike
