### ISSUE TITLE
Duckyscript generator

### ISSUE THREAD

**Issue by kar2013** [hak5darren/USB-Rubber-Ducky#16]
Hi',

Somebody can say me if it's possible de find a ducky auto script generator.
Like office macro or other.

Thanks

**Comment by mubix** [comment]
Sorry, not sure what you are asking for. Can you explain what you want it to do?

**Comment by SiemH** [comment]
Just google something like;
"Ducky payload generator"
Or use the "Simpele ducky payload generator"
Or use the duckencoder site, there is a payload generator aswell.
-Siem

**Comment by mubix** [comment]
Ok, I found this: https://code.google.com/p/simple-ducky-payload-generator/  still not sure what you are asking.

**Comment by SiemH** [comment]
I think that's what he's look'n 4.

**Comment by kar2013** [comment]
Dear all,

Thanks for your answers. I have an other question, when if flash my device with a script 
the output code give me an error and is different
 for example  "powershell" windows respond me "pozershell" don't exist
You have an idea ?

**Comment by SiemH** [comment]
Do you use the online encoder or encoder.jar,
Basicaly it converts it to a binary file (.bin)
You have to save it as inject.bin on the root of your SD, try encoding it again or try a different method.

**Comment by kar2013** [comment]
I use the jar encoder ! on a badusb key

**Comment by SiemH** [comment]
Then try the online encoder and see of it does anything different 
Also try it on different pcs
Else ask darren for tips.

**Comment by kar2013** [comment]
The online encoder is out !    http://www.ducktoolkit.com/

**Comment by mubix** [comment]
@kar2013 my bet is that you are using a system/keyboard that isn't natively en-US, which shouldn't matter, but it may be that the Java version you are running is seeing UNICODE characters in the text file and attempting to translate them incorrectly. 

https://ducktoolkit-411.rhcloud.com/Home.jsp  is the online encoder I think

**Comment by SiemH** [comment]
It moved to http://ducktoolkit-411.rhcloud.com/Encoder.jsp

**Comment by SiemH** [comment]
That's also why he should try it on different pcs

**Comment by kar2013** [comment]
it's possible to hide the action on screen?

**Comment by SiemH** [comment]
Darren made a video about that, search "Hide ducky attacks" on YT

**Comment by kar2013** [comment]
Thanks for all  answers

**Comment by SiemH** [comment]
NP
