### ISSUE TITLE
"\" not working in Windows 11

### ISSUE THREAD

**Issue by ManindraDeMel** [hak5darren/USB-Rubber-Ducky#180]
I've tried printing the mentioned characters "\" and ":" within the windows, 11 OS and it just doesn't work. There may be other characters that also experience this but am yet to come across it. 

`STRING New-Item -Path "HKLM:\SYSTEM\CurrentControlSet\Services\kbdhid" -Name crashdump`
Output:
`New-Item -Path "HKLMSYSTEMCurrentControlSetServiceskbdhid" -Name crashdump`

**Comment by ManindraDeMel** [comment]
Sorry, ":" seem to work, just not "\"

**Comment by TheContainer** [comment]
Check your keyboard language style
