### ISSUE TITLE
Windows defender

### ISSUE THREAD

**Issue by Reverrb** [hak5darren/USB-Rubber-Ducky#182]
I know you probably saw it a million times, but has there been any news to disabling tamper control yet? If so I'd like to know, thank you

**Comment by Reverrb** [comment]
Also you can only toggle the security switches with a mouse, keyboards don't work

**Comment by GamehunterKaan** [comment]
You Can Add Exclusion Path With  `Add-MpPreference -ExclusionPath (path)`

**Comment by Reverrb** [comment]
i honestly have no idea what that is, but if it helps someone else that's good

**Comment by GamehunterKaan** [comment]
Its a powershell command. In order to run this command you have to run powershell as administrator

**Comment by Reverrb** [comment]
what would the script look like then? I used the script already and it basically said (path) isn't compatible

**Comment by GamehunterKaan** [comment]
(path) is where you download your files at.For example if you want to download your files at temp directory you would have to run `Add-MpPreference -ExclusionPath $env:TEMP` 
[You can learn more about this command from microsoft](https://docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=windowsserver2022-ps)

**Comment by Reverrb** [comment]
I guess I'm a noob then. I'm still trying to find out how this will disable tamper control

**Comment by GamehunterKaan** [comment]
Tamper control doesn't care about this command.So you don't need to disable tamper control to run this command.
