### ISSUE TITLE
Mac CMD keyboard press 

### ISSUE THREAD

**Issue by diliboy88** [hak5darren/USB-Rubber-Ducky#183]

**Comment by Person2099** [comment]
I had the same issue. Try using [this encoder.](https://ducktoolkit.com/encode#)

I would try a simple script to test if it works, for example:

GUI q

**Comment by diliboy88** [comment]
Can you do CMD D ?

**Comment by Person2099** [comment]
> Can you do CMD D ?

Yeah, just replace CMD with GUI. (GUI d)

**Comment by diliboy88** [comment]
thanks!
