### ISSUE TITLE
Lacking files.

### ISSUE THREAD

**Issue by d3k4-k3rb3r0s** [hak5darren/USB-Rubber-Ducky#199]
multiple payloads posted here are equipped with dead links for files outside of github. first of all not just uploading it to github seems sketchy on behalf of the script author, but also on you guys for posting those links here. I guess my real frustration is that for a company charging 5 to 15 times what hardware is worth, that you would be able to find some time to keep the libraries supported. I get that we are all coders, but if I have to do more work on each payload to make it work than I would have done to write a working one from scratch, I just dont understand the point of this library.

**Comment by hak5darren** [comment]
@d3k4-k3rb3r0s you're right. This is a personal repo that I'm not keeping up-to-date as it's been superseded by those at github.com/hak5 and payloads.hak5.org. This is what happens when a wiki is public for 10+ years. Might I recommend you check out the above mentioned links.
