### ISSUE TITLE
Slow Down Ducky

### ISSUE THREAD

**Issue by jreed04** [hak5darren/USB-Rubber-Ducky#26]
We're trying to use the Ducky to change Bios settings on hundreds of computers.  Apparently, the computers cannot keep up with the speed that the ducky processes commands.  Our scripts, when including the delay command are about a mile long.  Is it possible to slow down the entire process of the Ducky without the delay commands?

**Comment by aott** [comment]
Did you have tried the command DEFAULT_DELAY?
Just put it at the begin of your script
`DEFAULT_DELAY  1000`
Now there is a delay of 1000 ms between each command.
If there is a DELAY command anywhere after that in the script it should override the delay between the previous command and the next command

**Comment by nileshp87** [comment]
Is there a way to slow down within a STRING? Calling STRING repetitively is a huge pain, and it seems STRINGDELAY and STRING_DELAY are both currently broken.
