### ISSUE TITLE
Bluetooth/Wireless Ducky Attacks

### ISSUE THREAD

**Issue by DarrenRainey** [hak5darren/USB-Rubber-Ducky#28]
I was looking at some of the stuff in kali nethunter including hid and ducky attacks so I was wondering if there was away of reprogramming or using a bluetooth dongle and remotely sending keystrokes such as in my remote my current solution is to remote connect to my nethunter device that is plugged into the target but the hardware is much more expensive that way as I need a nexus device etc for it

**Comment by AshtinBlanchard** [comment]
To clarify, what you are saying is to have a USB rubber ducky act as a bluetooth keyboard? If so, I believe there is likely a way to do that with a hardware attachment(non existent as of yet as far as I know), maybe, although I am not sure.

**Comment by pe64** [comment]
what?

**Comment by K1udg3** [comment]
I have been working on something like this on and off. Work and school has taken my attention but I was using a teensy and adding Bluetooth with a HC-05. I'll look around for my notes but I hade it working to a point. I could set key sequences to in a script that would execute by sending keys from a Bluetooth terrimanl on my laptop but couldn't get it to just mirror my keypad. Yet.

**Comment by AshtinBlanchard** [comment]
@K1udg3 you probably want to make the bluetooth dongle identify as a keyboard device, in which case youd need to do some firmware hacking on the dongle probably

**Comment by K1udg3** [comment]
I am using the teensy to act as a HID. Like the "USB drive by" the project that the ducky was based on if I'm not mistaken. The computer sees it as a keyboard just fine. And I have a HC-05 connected to the teensy to give it a Bluetooth input. I can send commands to the teensy via Bluetooth with a terminal Bluetooth app on my laptop. But I have yet to get the teensy to allow really time key injection. So I can program payloads the same as on the ducky and send something like 

If x = 1 
Then run y
and that will execute a  specific "inject.bin" so to speak and the same goes for any number of  variables. I hope that made it more clear.

**Comment by AshtinBlanchard** [comment]
@K1udg3 Ahh, alright, well there may be simpler/more compact ways to go about this, however, I do not know of them.

**Comment by adde88** [comment]
This might be possible using an Arduino, or a Digispark.
I've managed to get the Digispark to act as a Rubber Ducky.
And one could possibly solder on a bluetooth module to the Digispark, or some other arduino-compatible module. It would be awesome to see something as custom as that working. :)

**Comment by DarrenRainey** [comment]
yeah I've figured out that I can use an ardunio nano with a bluetooth module (HC-05) to wireless upload code to the arduino via bluetooth and I can convert ducky script to ardunio code using a modifed version of Dckuino.js

**Comment by miroatme** [comment]
There was a project called [The Glitch](http://theglitch.sourceforge.net)
that did cover this exact thing. It was a great little device that never
grew. I always thought it'd be a good evolution for the Rubber ducky.

Maybe that can give you some help and ideas.

**Comment by br0k3nilluzion** [comment]
The cost for these Bluetooth Ducky's is under $10..
