### ISSUE TITLE
help me please 

### ISSUE THREAD

**Issue by lawxi** [hak5darren/USB-Rubber-Ducky#40]
i recently received my rubber ducky, i was soon to create a script in the script generator, however now that i have the script i am unaware as to how to get the code onto the usb. any help would be greatly appreciated

**Comment by klugermtg** [comment]
Ha noob!

**Comment by Neyt** [comment]
the easiest way is to go to https://ducktoolkit.com/

you have to change the code from txt to a bin format (that url does it). and then you put that file into the mini sd card

**Comment by Hak5Jason** [comment]
Also check out this [video](https://www.youtube.com/watch?v=NeDYD9nb7PM).
