### ISSUE TITLE
LED Controll Like Bash Bunny any ideas ?

### ISSUE THREAD

**Issue by Blackbeard1st** [hak5darren/USB-Rubber-Ducky#59]
the title it says

**Comment by rpborges97** [comment]
Hey, can you explain a bit more the concept?

**Comment by Blackbeard1st** [comment]
i was looking for an oppertunity to add more Ducky commands like on the bash bunny this -> LED R ... for Red or switch LED collor like Red stay Red blink Green blink Green stay or stay GR for bouth... I would like to have this on the Ducky if possible. I was not able to figure out the sourcecode. 

i think the bunny is to big, to slow (couse boot up for ducky attck), a little expensive
